<?php

namespace AppBundle\Repository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUploadDateRangeWithCategory(\DateTime $start, \DateTime $end){
		$qb = $this
		->createQueryBuilder('o')
		->innerJoin('o.objectCategoryId','cat')
		->addSelect('cat');
		;

		$qb
		->where('o.objectUploadDate >= :start')
		->setParameter('start', $start)
		->andWhere('o.objectUploadDate <= :end')
		->setParameter('end', $end)
		->orderBy('o.objectUploadDate','DESC');

		return $qb->getQuery()->getResult();
	}

	public function getObjectsWithCategory(array $categoryFilter){
		$qb = $this
		->createQueryBuilder('o')
		->innerJoin('o.objectCategoryId','cat')
		->addSelect('cat')
		;

		$qb->where($qb->expr()->in('o.objectCategoryId', $categoryFilter));

		return $qb
		->getQuery()
		->getResult()
		;
	}
}

?>