<?php

namespace AppBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalizationRepository extends \Doctrine\ORM\EntityRepository
{
	//Recupere les personnalisation de l utilisateur avec l id $userId et concernant les objets de categorie $categoryFilter
	public function getUserPersonalizationsWithObjects($userId, $categoryFilter = null){
		$qb = $this
		->createQueryBuilder('pur')
		->innerJoin('pur.object','obj')
		->addSelect('obj')
		->innerJoin('obj.objectCategoryId','cat')
		->addSelect('cat')
		;

		$qb->where($qb->expr()->eq('pur.user',$userId));
		if($categoryFilter != null){
			$qb->andWhere($qb->expr()->eq('obj.objectCategoryId', $categoryFilter));
		}

		return $qb
		->getQuery()
		->getResult()
		;
	}
}

?>