<?php

namespace AppBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserPurchasesWithObjects($userId){
		$qb = $this
		->createQueryBuilder('p')
		->innerJoin('p.object','obj')
		->addSelect('obj')
		->innerJoin('obj.objectCategoryId','cat')
		->addSelect('cat')
		;

		$qb->where($qb->expr()->eq('p.user',$userId));

		return $qb
		->getQuery()
		->getResult()
		;
	}
}

?>