<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	//Recupere le nombre d utilisateur dans la base de donnees
	public function getUserCount(){
		$query = $this->getEntityManager()->createQueryBuilder()
		->select('COUNT(u.userId)')
		->from('AppBundle:User','u')
		->getQuery();

		return $query->getSingleScalarResult();
	}
	//Recupere les utilisateurs dont le login ressemble a celui passe en parametre par $userAlikeLogin
	public function getProbableUsers($userAlikeLogin){
		$qb = $this->createQueryBuilder('u');
		$query = $qb
		->where($qb->expr()->like('u.userLogin',':userAlikeLogin'))
		->setParameter('userAlikeLogin','%'.$userAlikeLogin.'%')
		->getQuery()
		;

		return $query->getArrayResult();
	}
}

?>